apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 1
  selector:
    matchlabel:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: flowerking21/learnersreport_backend:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4200




