apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.backendname }}

spec:
  replicas: 1
  selector:
    matchlabel:
      app: {{ .Values.deployments.backendname }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.backendname }}
    spec:
      containers:
        - name: {{ .Values.deployments.backendname }}
          image: "{{ .Values.image.backend.repository }}/{{ .Values.image.backend.name }}:{{ .Values.image.backend.tag }}"
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
              cpu: {{ .Values.resources.cpu }}
          ports:
            - containerPort: {{ .Values.image.backend.port }}




