apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.frontendname }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.deployments.frontendname }}
  ports:
  - port: {{ .Values.image.frontend.Port }}
    targetPort: {{ .Values.image.frontend.port }}
